#!/bin/bash
set -e

if [ "$1" = "configure" ]; then
    mkdir -p /opt/mema
    mkdir -p /etc/mema/recipes
    
    chmod 755 /opt/mema
    chmod 755 /etc/mema
    chmod 755 /etc/mema/recipes

    echo "Mema: Basic directory structure initialized in /opt/mema"
fi

exit 0
